server:
    port: 8080
    address: localhost

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hrs_register
        username: root
        password: 123

#        spring:
#            datasource:
#                url: jdbc:mysql://192.168.3.230:3309/hrs_register?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#                username: hrs_register
#                password: 1_IWCm_LCQj66G4k